DROP TABLE USERS;

CREATE TRIGGER TRIGGER_USERS
    BEFORE INSERT
    ON USERS
    FOR EACH ROW
DECLARE
    v_count INT;

BEGIN
    SELECT Count(*) INTO v_count FROM USERS WHERE LOWER(USERNAME) = LOWER(:NEW.USERNAME);
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'USER already exists');
    END IF;
END;

--ATENTIE CUM IL APLIC
CREATE TRIGGER TRIGGER_USERSUPDATE
    BEFORE UPDATE
    ON USERS
    FOR EACH ROW
DECLARE
    v_count INT;

BEGIN
    SELECT Count(*) INTO v_count FROM USERS WHERE LOWER(USERNAME) = LOWER(:NEW.USERNAME);
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Wrong update');
    END IF;
END;

DROP TABLE USERS;
CREATE TABLE USERS
(
    id        INT          NOT NULL,
    username  VARCHAR(100) NOT NULL,
    firstname VARCHAR(100) NOT NULL,
    lastname  VARCHAR(100) NOT NULL,
    phone     VARCHAR(100) NOT NULL,
    password  VARCHAR(100) NOT NULL,
    email     VARCHAR(100) NOT NULL,
    address   VARCHAR(100) NOT NULL,
    role      VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

--SELECT * FROM USERS;
--DELETE FROM USERS WHERE id = 12;re